name: Run TPU tests
on:
  push:
    paths-ignore: ['*.txt']
  pull_request:
    paths-ignore: ['*.txt]


jobs:
  tpu-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        xla-version: [nightly, ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.10'
        architecture: 'x64'
