name: Code format
on: push
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - run: |
        python -m pip install autopep8 "black==19.10b0" "isort==4.3.21"
        isort -rc .
        autopep8 --recursive --in-place --aggressive --aggressive .
        black .
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v2.0.0
      with:
        COMMIT_AUTHOR_EMAIL: ''
        COMMIT_AUTHOR_NAME: 'AutoPEP8'
        COMMIT_MESSAGE: 'autopep8 fix'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}