name: ContributorSpecFailure
on: 
  workflow_run:
    workflows:
      - ContributorSpec
    types:
       - completed
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - env:
          CONTEXT: ${{ toJSON(github) }}
        run: echo $CONTEXT
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow.id }}
      - run: echo "##[set-output name=id;]$(jq '.event.number' ${{ github.event.workflow_run.id }}/data.json)"
        id: pull_request
      - run: jq '.event.number' ${{ github.event.workflow_run.id }}/data.json
      - run: jq '.' ${{ github.event.workflow_run.id }}/data.json
      - env:
          TEST:  steps.pull_request.outputs.id
        run: echo $TEST  
      - if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.pull_request.outputs.id }} 
          body: |
            It looks like you haven't order the JSON values in **ascending order alphabetically ignoring case** by Github user name or your JSON syntax is wrong. Please read the issue description before taking them.

            If you know about nodejs run the following command to sort the list:
            ```sh
              npx sort-json contributors.json --ignore-case
            ```

            **If you don't know about node js, go the following link:**
            https://codeshack.io/json-sorter/
            Paste the content of the file and generate a sorted JSON. After the paste the sorted list in the file and make a commit.


            Once this is done, your PR will be reviewed and merged.


            If you still have problem you can tag in a maintainer: @subeshb1
          reactions: eyes, -1, confused
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.pull_request.outputs.id }} 
          body: |
            Great! Your PR has succesfully passed all the checks. 🚀
            Your PR will be merged by a maintainer. Please be patience.
            In the mean while checkout the issues for anything you can help out on: [Issues needed Help](https://github.com/subeshb1/developer-community-stats/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)
          reactions: heart, hooray, +1, rocket
